<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="runtimePatterns" nsURI="http://mondo.org/runtimePatterns" nsPrefix="rtpat">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="dslPatterns" value="http://mondo.org/dslPatterns#/"/>
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore#/"/>
    <details key="rtServ" value="http://mondo.org/runtimeServices#/"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PatternInstances">
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedPatterns" ordered="false"
        upperBound="-1" eType="#//PatternInstance" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PatternInstance">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ident" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="pattern" eType="ecore:EClass http://mondo.org/dslPatterns#//Pattern"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classInstances" ordered="false"
        upperBound="-1" eType="#//ClassRoleInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serviceInstances" ordered="false"
        upperBound="-1" eType="ecore:EClass http://mondo.org/runtimeServices#//ServiceInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleInstance" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassRoleInstance" eSuperTypes="#//RoleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="ecore:EClass http://mondo.org/dslPatterns#//ClassInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featureInstances" upperBound="-1"
        eType="#//FeatureRoleInstance"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceInstances" upperBound="-1"
        eType="#//ReferenceRoleInstance"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureRoleInstance" abstract="true"
      eSuperTypes="#//RoleInstance"/>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceFeatureRoleInstance" eSuperTypes="#//FeatureRoleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="ecore:EClass http://mondo.org/dslPatterns#//FeatureInstance"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeFeatureRoleInstance" eSuperTypes="#//FeatureRoleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="ecore:EClass http://mondo.org/dslPatterns#//FeatureType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EAttribute"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceRoleInstance" eSuperTypes="#//RoleInstance">
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" eType="ecore:EClass http://mondo.org/dslPatterns#//ReferenceInterface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EReference"/>
  </eClassifiers>
</ecore:EPackage>
